#!/usr/bin/env bash
# Validate the public ORKS organization defaults with local command-line tools.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
FAILURES=0
cd "$REPO_ROOT"

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  FAILURES=$((FAILURES + 1))
}

# The two capability roots installed from the pinned Orca baseline. Content
# beneath them is vendored: this repository does not author it and cannot edit
# it without breaking the lockfile hash it is pinned by. Section 6 bounds what
# may appear there and section 7 constrains its provenance and encoding; the
# narrow exemptions below name these roots and nothing else.
VENDOR_ROOTS=(.agents .claude)

# The generated entry points are required here alongside the authored rules
# file, and none of the fifteen community-health entries below is relaxed to
# make room for them. `RULES.md` is authority-chain entry 14; `AGENTS.md` and
# `CLAUDE.md` are its materializations under CANON-008 section 5. Requiring all
# three closes the window this list had between the 2026-08-13 relocation and
# the generator run, in which nothing in this repository required an entry point
# to exist at all.
printf '1. Required community files\n'
for path in \
  RULES.md \
  AGENTS.md \
  CLAUDE.md \
  README.md \
  LICENSE \
  NOTICE \
  CONTRIBUTING.md \
  DCO.md \
  CODE_OF_CONDUCT.md \
  SECURITY.md \
  SUPPORT.md \
  profile/README.md \
  .github/PULL_REQUEST_TEMPLATE.md \
  .github/ISSUE_TEMPLATE/config.yml \
  .github/ISSUE_TEMPLATE/bug_report.yml \
  .github/ISSUE_TEMPLATE/conduct_report.yml \
  .github/ISSUE_TEMPLATE/feature_request.yml
do
  [ -f "$REPO_ROOT/$path" ] || fail "missing required file: $path"
done

printf '2. Shell and filesystem safety\n'
bash -n "$REPO_ROOT/scripts/validate-docs.sh" || fail "invalid validator syntax"
symlink="$(find "$REPO_ROOT" -type l -print -quit)"
[ -z "$symlink" ] || fail "repository symlink is not allowed: $symlink"
[ -x "$REPO_ROOT/scripts/validate-docs.sh" ] || fail "validator must be executable"
[ ! -e "$REPO_ROOT/.gitmodules" ] || fail "submodules are not allowed"
nested_git="$(find "$REPO_ROOT" -mindepth 2 -name .git -print -quit)"
[ -z "$nested_git" ] || fail "nested Git repository is not allowed: $nested_git"
[ ! -d "$REPO_ROOT/.github/workflows" ] || fail "workflows require separate approval"
for forbidden in codex.config.json claude.config.json directus.config.json; do
  match="$(find "$REPO_ROOT" -name "$forbidden" -print -quit)"
  [ -z "$match" ] || fail "forbidden runtime config: $match"
done

printf '3. Markdown links\n'
while IFS= read -r markdown; do
  while IFS= read -r raw_link; do
    target="${raw_link#*(}"
    target="${target%)}"
    target="${target%%#*}"
    target="${target#<}"
    target="${target%>}"
    case "$target" in
      ""|\#*|http://*|https://*|mailto:*|/*) continue ;;
    esac
    if [ ! -e "$(dirname "$markdown")/$target" ]; then
      fail "broken link in ${markdown#"$REPO_ROOT/"}: $target"
    fi
  done < <(grep -oE '\[[^]]+\]\([^)]*\)' "$markdown" || true)
done < <(find "$REPO_ROOT" -type f -name '*.md' \
  -not -path '*/.git/*' \
  -not -path "$REPO_ROOT/.agents/*" \
  -not -path "$REPO_ROOT/.claude/*" \
  -print | LC_ALL=C sort)
# The capability roots are exempt from the link sweep, and only from this one.
# Two installed capabilities carry a relative link into the distribution's own
# tree (`../lessons/archive/...`), which cannot resolve in any consumer. That is
# a defect in the distribution, not in this repository, and it is reported
# upstream rather than repaired here.

printf '4. Public-content boundary\n'
# ASCII is this repository's own rule and it still binds every authored file.
# The capability roots are exempt because their content is generated by a
# distribution this repository does not own; section 7 holds them to valid
# UTF-8 with no NUL instead, which is the floor that actually protects a
# reader.
if rg -n '[^\x00-\x7F]' "$REPO_ROOT" --hidden --glob '!.git' --glob '!.git/**' \
  --glob '!.agents/**' --glob '!.claude/**' >/dev/null; then
  fail "non-ASCII content found"
fi
if rg -n '\r$' "$REPO_ROOT" --hidden --glob '!.git' --glob '!.git/**' >/dev/null; then
  fail "CRLF line ending found"
fi
if rg -n '\b(TODO|TBD|FIXME|XXX)\b' "$REPO_ROOT" \
  --hidden --glob '!.git' --glob '!.git/**' --glob '!scripts/validate-docs.sh' >/dev/null; then
  fail "unresolved placeholder marker found"
fi
# The combined pattern is split so the two halves can be exempted separately.
# Host paths and credential markers are the security half and are enforced
# everywhere, including the capability roots and the lockfile, with no
# exemption beyond this script's own text. Measured: the installed payload is
# clean of both.
if rg -n '(/home/|BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY)' \
  "$REPO_ROOT" --hidden --glob '!.git' --glob '!.git/**' \
  --glob '!scripts/validate-docs.sh' >/dev/null; then
  fail "private path or credential marker found"
fi
# External-authority names are the boundary half. They are exempt inside the
# capability roots, where they occur as vendored prose, and inside
# `skills-lock.json`, where they are the required provenance the lockfile must
# carry. Section 7 constrains that lockfile text positively rather than
# ignoring it.
if rg -n '(ProbablyComputers|pc-standards|Directus)' \
  "$REPO_ROOT" --hidden --glob '!.git' --glob '!.git/**' \
  --glob '!scripts/validate-docs.sh' --glob '!skills-lock.json' \
  --glob '!.agents/**' --glob '!.claude/**' >/dev/null; then
  fail "external authority reference found outside the capability roots"
fi

printf '5. Template structure\n'
if command -v yamllint >/dev/null 2>&1; then
  if ! yamllint -d '{extends: relaxed, rules: {line-length: disable}}' \
    "$REPO_ROOT/.github/ISSUE_TEMPLATE/bug_report.yml" \
    "$REPO_ROOT/.github/ISSUE_TEMPLATE/conduct_report.yml" \
    "$REPO_ROOT/.github/ISSUE_TEMPLATE/config.yml" \
    "$REPO_ROOT/.github/ISSUE_TEMPLATE/feature_request.yml"; then
    fail "issue template YAML is invalid"
  fi
else
  printf 'SKIP: yamllint is unavailable; running structural checks only\n'
fi
for form in bug_report.yml feature_request.yml; do
  path="$REPO_ROOT/.github/ISSUE_TEMPLATE/$form"
  rg -q '^name:' "$path" || fail "$form lacks name"
  rg -q '^description:' "$path" || fail "$form lacks description"
  rg -q '^body:' "$path" || fail "$form lacks body"
  rg -q 'Code of Conduct' "$path" || fail "$form lacks conduct confirmation"
done
rg -q '^name: Code of Conduct report$' \
  "$REPO_ROOT/.github/ISSUE_TEMPLATE/conduct_report.yml" || \
  fail "conduct report form is missing"
rg -q 'This issue is public' \
  "$REPO_ROOT/.github/ISSUE_TEMPLATE/conduct_report.yml" || \
  fail "conduct report form lacks public-content warning"
rg -q '^blank_issues_enabled: false$' \
  "$REPO_ROOT/.github/ISSUE_TEMPLATE/config.yml" || \
  fail "blank issues must remain disabled"
rg -q 'Signed-off-by' "$REPO_ROOT/.github/PULL_REQUEST_TEMPLATE.md" || \
  fail "pull request template lacks DCO confirmation"
rg -q 'Developer Certificate of Origin' "$REPO_ROOT/CONTRIBUTING.md" || \
  fail "contribution guidance lacks DCO 1.1 policy"
rg -q 'Version 1.1' "$REPO_ROOT/DCO.md" || fail "DCO version is not 1.1"
rg -q 'Apache License' "$REPO_ROOT/LICENSE" || fail "Apache license text missing"
rg -q 'Adam Claassens' "$REPO_ROOT/NOTICE" || fail "public attribution missing"
rg -q 'private vulnerability reporting' "$REPO_ROOT/SECURITY.md" || \
  fail "security policy lacks private vulnerability reporting"
rg -q 'Do not include vulnerability details' "$REPO_ROOT/SECURITY.md" || \
  fail "security policy lacks public-disclosure warning"
rg -q 'best-effort' "$REPO_ROOT/SUPPORT.md" || \
  fail "support policy lacks best-effort scope"

printf '6. Vendor capability roots\n'
LOCK="$REPO_ROOT/skills-lock.json"
if [ ! -f "$LOCK" ]; then
  fail "missing required file: skills-lock.json"
else
  # Names are read from `skillPath` rather than from object keys, so the read
  # does not depend on the lockfile's indentation, and so a malformed entry is
  # caught by the key-count agreement below instead of being skipped in
  # silence.
  lock_names="$(grep -oE '"skillPath"[[:space:]]*:[[:space:]]*"skills/[^"/]+/SKILL\.md"' "$LOCK" \
    | sed -E 's#.*"skills/([^"/]+)/SKILL\.md"#\1#' | LC_ALL=C sort)"
  lock_count="$(printf '%s\n' "$lock_names" | grep -c . || true)"
  source_count="$(grep -c '"source"[[:space:]]*:' "$LOCK" || true)"
  type_count="$(grep -c '"sourceType"[[:space:]]*:' "$LOCK" || true)"
  hash_count="$(grep -c '"computedHash"[[:space:]]*:' "$LOCK" || true)"
  [ "$lock_count" -gt 0 ] || fail "skills-lock.json declares no capability"
  if [ "$lock_count" -ne "$source_count" ] || [ "$lock_count" -ne "$type_count" ] \
    || [ "$lock_count" -ne "$hash_count" ]; then
    fail "skills-lock.json entries are incomplete: $lock_count skillPath, $source_count source, $type_count sourceType, $hash_count computedHash"
  fi

  # No globally-scoped and no execution-role capability may be installed into
  # this repository. This is the documented silent-widening failure: a filter
  # matching nothing installs the whole distribution, exits 0, and produces a
  # lockfile that is internally consistent and wrong.
  while IFS= read -r name; do
    [ -n "$name" ] || continue
    case "$name" in
      orca-bootstrap)
        fail "globally-scoped capability installed into the project: $name" ;;
      orca-role-contract) ;;
      orca-role-*)
        fail "execution-role capability is not declared for this repository: $name" ;;
    esac
  done <<EOF
$lock_names
EOF

  # Exact accounting in both directions: every lockfile entry resolves under
  # both roots, and every path under either root is named by the lockfile.
  # Nothing else is admitted beneath a capability root - an unbounded vendor
  # directory is how unreviewed instruction text reaches an agent while every
  # other check stays green.
  for root in "${VENDOR_ROOTS[@]}"; do
    if [ ! -d "$REPO_ROOT/$root" ]; then
      fail "missing capability root: $root/skills"
      continue
    fi
    while IFS= read -r name; do
      [ -n "$name" ] || continue
      [ -f "$REPO_ROOT/$root/skills/$name/SKILL.md" ] || \
        fail "capability declared by the lockfile is absent: $root/skills/$name/SKILL.md"
    done <<EOF
$lock_names
EOF
    while IFS= read -r found; do
      relative="${found#"$REPO_ROOT/"}"
      entry="${relative#"$root/skills/"}"
      case "$relative" in
        "$root/skills/"*/SKILL.md)
          name="${entry%/SKILL.md}"
          case "$name" in
            */*) fail "capability root is not bounded to one level: $relative"; continue ;;
          esac
          printf '%s\n' "$lock_names" | grep -qx "$name" || \
            fail "file under a capability root is not named by the lockfile: $relative"
          ;;
        *) fail "unexpected file under a capability root: $relative" ;;
      esac
    done < <(find "$REPO_ROOT/$root" -type f -print | LC_ALL=C sort)
  done

  # The two roots hold real files rather than symlinks, because section 2
  # refuses a symlink outright and that refusal is a control worth keeping.
  # The cost of the duplication is that the roots can diverge silently, and
  # this is the check that answers it.
  while IFS= read -r name; do
    [ -n "$name" ] || continue
    left="$REPO_ROOT/.agents/skills/$name/SKILL.md"
    right="$REPO_ROOT/.claude/skills/$name/SKILL.md"
    if [ -f "$left" ] && [ -f "$right" ]; then
      cmp -s "$left" "$right" || fail "capability roots disagree: $name"
    fi
  done <<EOF
$lock_names
EOF

  printf '7. Capability provenance and encoding\n'
  # Provenance is required text, not merely permitted text. Every entry must
  # name the pinned distribution over GitHub; a lockfile recording a filesystem
  # path is a defective install however complete it otherwise looks.
  provenance_count="$(grep -c '"source"[[:space:]]*:[[:space:]]*"ProbablyComputers/orca-baseline"' "$LOCK" || true)"
  [ "$provenance_count" -eq "$lock_count" ] || \
    fail "skills-lock.json must record ProbablyComputers/orca-baseline for every capability: $provenance_count of $lock_count"
  github_count="$(grep -c '"sourceType"[[:space:]]*:[[:space:]]*"github"' "$LOCK" || true)"
  [ "$github_count" -eq "$lock_count" ] || \
    fail "skills-lock.json must record github provenance for every capability: $github_count of $lock_count"
  # The external-authority exemption granted in section 4 is bounded here: the
  # only occurrences the lockfile may carry are the provenance values counted
  # above.
  other_authority="$(grep -c '\(pc-standards\|Directus\)' "$LOCK" || true)"
  [ "$other_authority" -eq 0 ] || \
    fail "skills-lock.json carries an external authority reference that is not provenance"
  stray_authority="$(grep -o 'ProbablyComputers[^"]*' "$LOCK" | grep -vxc 'ProbablyComputers/orca-baseline' || true)"
  [ "$stray_authority" -eq 0 ] || \
    fail "skills-lock.json carries a ProbablyComputers reference that is not the pinned distribution"

  # Section 4 exempts the capability roots from the ASCII rule. This is the
  # floor that replaces it: decodable text with no embedded NUL.
  while IFS= read -r found; do
    relative="${found#"$REPO_ROOT/"}"
    if ! iconv -f UTF-8 -t UTF-8 "$found" >/dev/null 2>&1; then
      fail "capability content is not valid UTF-8: $relative"
    fi
    if [ "$(tr -d '\000' <"$found" | wc -c)" -ne "$(wc -c <"$found")" ]; then
      fail "capability content contains a NUL byte: $relative"
    fi
  done < <(find "$REPO_ROOT/.agents" "$REPO_ROOT/.claude" -type f -print 2>/dev/null | LC_ALL=C sort)
fi

if [ "$FAILURES" -ne 0 ]; then
  printf 'FAILED: %s validation issue(s)\n' "$FAILURES" >&2
  exit 1
fi

printf 'PASS: ORKS organization community documentation validation\n'
